
FROM openjdk:17-oracle
#EXPOSE 8081
#ARG JAR_FILE=target/*.jar
#COPY ${JAR_FILE} commondtos-service.jar
WORKDIR /app
# ARG JAR_FILE=target/*.jar
# COPY ${JAR_FILE} /app/commondtos-service.jar
# COPY common-service/target/common-service.jar /app/app.jar
# COPY target/classes /app/classes
# WORKDIR /app
# ENTRYPOINT ["java","-jar","commondtos-service.jar"]

COPY target/classes /app/data




